---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    stable.k8s.psg.io/kcm.class: default
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/whitelist-source-range: "{{.WHITELIST}}"
    stable.k8s.psg.io/kcm.provider: http
    ingress.kubernetes.io/enable-modsecurity: "true"
    ingress.kubernetes.io/enable-owasp-modsecurity-crs: "true"
  name: pttg-rps-enquiry-ingress-external-govuk
spec:
  tls:
  - hosts:
    - {{.DOMAIN_NAME}}
    secretName: letsencrypt-pttg-rps-enquiry
  rules:
  - host: {{.DOMAIN_NAME}}
    http:
      paths:
      - backend:
          serviceName: pttg-rps-enquiry
          servicePort: 443
        path: /
