---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    stable.k8s.psg.io/kcm.class: default
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/whitelist-source-range: "{{.WHITELIST}}"
    stable.k8s.psg.io/kcm.provider: http
  name: pttg-rps-enquiry-ingress-external
spec:
  tls:
  - hosts:
    - settlement-enquiry-form.eue.homeoffice.gov.uk
    secretName: letsencrypt-pttg-rps-enquiry
  rules:
  - host: {{.DOMAIN_NAME}}
    http:
      paths:
      - backend:
          serviceName: pttg-rps-enquiry
          servicePort: 443
        path: /
