---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pttg-rps-enquiry-ingress-external
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    cert-manager.io/enabled: "true"
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/session-cookie-name: ingress
    ingress.kubernetes.io/enable-modsecurity: "true"
    ingress.kubernetes.io/enable-owasp-modsecurity-crs: "true"
    ingress.kubernetes.io/whitelist-source-range: {{ .WHITELIST | quote}}
  labels:
    cert-manager.io/solver: http01
spec:
  tls:
  - hosts:
    - {{ .DOMAIN_NAME | quote }}
    secretName: "letsencrypt-{{ .DEPLOYMENT_NAME }}-cmio"
  rules:
  - host: {{ .DOMAIN_NAME | quote }}
    http:
      paths:
      - backend:
          serviceName: {{ .DEPLOYMENT_NAME | quote }}
          servicePort: 443
        path: /
