---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pttg-rps-enquiry-maintenance
  labels:
    version: {{.VERSION}}
spec:
  replicas: 2
  selector:
    matchLabels:
      name: pttg-rps-enquiry-maintenance
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: pttg-rps-enquiry-maintenance
        version: {{.VERSION}}
    spec:
      containers:
      - name: certs
        image: quay.io/ukhomeofficedigital/cfssl-sidekick:v0.0.6
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        args:
          - --certs=/certs
          - --domain=pttg-rps-enquiry-maintenance.${KUBE_NAMESPACE}.svc.cluster.local
          - --expiry=8760h
          - --command=/usr/local/scripts/trigger_nginx_reload.sh
        env:
          - name: KUBE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: certs
            mountPath: /certs
          - name: bundle
            mountPath: /etc/ssl/certs
            readOnly: true
      - name: proxy
        image: quay.io/ukhomeofficedigital/pttg-rps-enquiry-proxy:build-19
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        resources:
          limits:
            memory: "100Mi"
            cpu: 100m
          requests:
            memory: "50Mi"
            cpu: 100m
        env:
          - name: PROXY_SERVICE_HOST
            value: '127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '8080'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
          - name: HTTPS_REDIRECT
            value: 'FALSE'
          - name: SERVER_CERT
            value: /certs/tls.pem
          - name: SERVER_KEY
            value: /certs/tls-key.pem
          - name: ADD_NGINX_SERVER_CFG
            value: 'gzip off; location = /reload { allow 127.0.0.1; deny all; content_by_lua_block { os.execute("touch /tmp/nginx-reload-triggered; /usr/local/openresty/nginx/sbin/nginx -s reload; touch /tmp/nginx-reload-complete;") } }'
        volumeMounts:
          - name: certs
            mountPath: /certs
            readOnly: true
        ports:
          - name: https
            containerPort: 10443
      - name:  pttg-rps-enquiry-maintenance
        image: quay.io/ukhomeofficedigital/pttg-enquiry-form-maintenance:EE-28042-Language-Translation-Placement-on-Maintenance-Page
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        resources:
          limits:
            memory: "100Mi"
            cpu: 100m
          requests:
            memory: "50Mi"
            cpu: 100m
        ports:
          - name: http
            containerPort: 8080
      volumes:
        - name: certs
          emptyDir:
            medium: "Memory"
        - name: bundle
          configMap:
            name: bundle
