---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pttg-rps-enquiry
  labels:
    version: {{.VERSION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pttg-rps-enquiry
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: pttg-rps-enquiry
        version: {{.VERSION}}
    spec:
      containers:
      - name: certs
        image: quay.io/ukhomeofficedigital/cfssl-sidekick:v0.0.6
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        args:
          - --certs=/certs
          - --domain=pttg-rps-enquiry.${KUBE_NAMESPACE}.svc.cluster.local
          - --expiry=8760h
          - --command=/usr/local/scripts/trigger_nginx_reload.sh
        env:
          - name: KUBE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: certs
            mountPath: /certs
          - name: bundle
            mountPath: /etc/ssl/certs
            readOnly: true
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy:v3.2.9
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        resources:
          limits:
            memory: "100Mi"
            cpu: 100m
          requests:
            memory: "50Mi"
            cpu: 100m
        env:
          - name: PROXY_SERVICE_HOST
            value: '127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '9000'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
          - name: HTTPS_REDIRECT
            value: 'FALSE'
          - name: SERVER_CERT
            value: /certs/tls.pem
          - name: SERVER_KEY
            value: /certs/tls-key.pem
          - name: ADD_NGINX_SERVER_CFG
            value: 'gzip off; location = /reload { allow 127.0.0.1; deny all; content_by_lua_block { os.execute("touch /tmp/nginx-reload-triggered; /usr/local/openresty/nginx/sbin/nginx -s reload; touch /tmp/nginx-reload-complete;") } }'
        volumeMounts:
          - name: certs
            mountPath: /certs
            readOnly: true
        ports:
          - name: https
            containerPort: 10443
      - name: keycloak-proxy
        image: quay.io/ukhomeofficedigital/go-keycloak-proxy:v2.1.1
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            memory: "100Mi"
            cpu: 100m
          requests:
            memory: "50Mi"
            cpu: 100m
        args:
          - --config=/etc/secrets/keycloak-api-secret.yaml
          - --discovery-url=https://sso.digital.homeoffice.gov.uk/auth/realms/{{.KC_REALM}}
          - --client-id=pttg-rps-{{.ENVIRONMENT}}
          - --listen=127.0.0.1:9000
          - --enable-logging=true
          - --enable-json-logging=true
          - --upstream-url=http://127.0.0.1:8080
          - --no-redirects=false
          - --redirection-url=https://{{.DOMAIN_NAME}}
          - --cors-origins='*'
          - --resources=uri=/healthz|white-listed=true
          - --resources=uri=/|methods=GET|roles=pttg-rps
          - --secure-cookie=true
          - --http-only-cookie=true
          - --verbose
        ports:
          - name: keycloak-http
            containerPort: 9000
        volumeMounts:
          - name: keycloak-api-secret
            mountPath: /etc/secrets
            readOnly: true
      - name: redis
        image: quay.io/ukhomeofficedigital/redis:v0.1.2
        ports:
          - containerPort: 6379
        env:
          - name: REDIS_PASSWORD
            value: password
#        command: ['/usr/bin/bash']
#        args: ['-c', 'echo "requirepass ${REDIS_PASSWORD}" >> /etc/redis.conf && /run.sh']
        volumeMounts:
          - mountPath: /var/lib/redis
            name: data
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
      - name: pttg-rps-enquiry
        image: quay.io/ukhomeofficedigital/pttg-rps-enquiry:{{.VERSION}}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        env:
          - name: CA_CERTS_PATH
            value: "/certs/tls.pem"
          - name: PROXY_REDIRECTION_URL
            value: https://{{.DOMAIN_NAME}}
          - name: NOTIFY_API_KEY
            valueFrom:
              secretKeyRef:
                name: notify-credentials
                key: api-key
          - name: NOTIFY_TEMPLATE_USER_CONFIRMATION
            value: 7134a896-2051-4a49-b71c-576325f4cf5c
          - name: NOTIFY_TEMPLATE_ENQUIRY_SUPPORT
            value: bb443ca9-b776-4853-81f3-4ba1727dc23e
        resources:
          limits:
            cpu: 1000m
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
        ports:
          - name: http
            containerPort: 8080
        volumeMounts:
          - mountPath: /certs
            name: certs
            readOnly: true
        livenessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: X-probe
              value: kubelet
            path: /healthz/ping
            port: http
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
      volumes:
        - name: data
          emptyDir: {}
        - name: certs
          emptyDir:
            medium: "Memory"
        - name: keycloak-api-secret
          secret:
            secretName: keycloak-api-secret
        - name: bundle
          configMap:
            name: bundle
