---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pttg-rps-contact
  name: pttg-rps-contact
spec:
  ports:
  - name: https
    port: 443
    targetPort: 10443
  selector:
    name: pttg-rps-contact
